/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Movie_Ticket.GUI;

import Movie_Ticket.DAO.MovieDao;
import Movie_Ticket.DAO.TicketDAO;
import Movie_Ticket.POJO.Movies;
import Movie_Ticket.POJO.Tickets;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;
import javax.swing.JOptionPane;

/**
 *
 * @author ankitjain
 */
public class BookTicketFrame extends javax.swing.JFrame {

    /**
     * Creates new form BookTicketFrame
     */
    private String mov_name;
    private String user_name;
    private String contact;
    private String screen;
    private double price;
    private int ticket;
    private Date ticket_date;
    Movies m=null;
    HashMap<String,Movies> map=null;
    public BookTicketFrame() {
        initComponents();
        setLocationRelativeTo(null);
        loadMovieName();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtContact = new javax.swing.JTextField();
        txtUser_name = new javax.swing.JTextField();
        txtTicket = new javax.swing.JTextField();
        txtScreen = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        btnBookTickt = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jcMov_name = new javax.swing.JComboBox<>();
        jDate = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Movie Name");

        jLabel2.setText("Booking Date");

        jLabel3.setText("User Name");

        jLabel4.setText("Contact");

        jLabel5.setText("Tickets");

        jLabel6.setText("Screen No.");

        jLabel7.setText("Price");

        txtScreen.setEditable(false);

        txtPrice.setEditable(false);

        btnBookTickt.setText("Book Ticket");
        btnBookTickt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookTicktActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jcMov_name.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        jcMov_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcMov_nameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnBookTickt)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtContact)
                            .addComponent(txtUser_name)
                            .addComponent(txtTicket)
                            .addComponent(txtScreen)
                            .addComponent(txtPrice)
                            .addComponent(jcMov_name, 0, 126, Short.MAX_VALUE)
                            .addComponent(jDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jcMov_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtUser_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtTicket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtScreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBookTickt)
                    .addComponent(btnBack))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcMov_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcMov_nameActionPerformed
        // TODO add your handling code here:
       String item=(String)jcMov_name.getSelectedItem();
       
       m=map.get(item);
       if(m==null)
       {
        JOptionPane.showMessageDialog(this,"Please select any movie!!");
        return;
       }
       txtScreen.setText(m.getScreen());
       System.out.println(m.getScreen());
       txtPrice.setText(String.valueOf(m.getPrice()));
       
    }//GEN-LAST:event_jcMov_nameActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        UserOptionsFrame user = new UserOptionsFrame();
        user.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnBookTicktActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookTicktActionPerformed
        // TODO add your handling code here:
        boolean isValidate = validateInput();
        if(!isValidate)
        {
            JOptionPane.showMessageDialog(this,"Please fill all the Fields..","Error!",JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
           SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
           Tickets tikt = new Tickets();
           tikt.setMovie_name(mov_name);
           tikt.setTicket_date(sdf.format(ticket_date));
           tikt.setUser_name(user_name);
           tikt.setContact(contact);
           tikt.setTicket(ticket);
           tikt.setScreen_no(screen);
           tikt.setPrice(price);
           
           int bookings=TicketDAO.bookedTickets(tikt.getTicket_date(),tikt.getMovie_name());
           
           System.out.println(bookings);
           System.out.println(bookings+tikt.getTicket());
           System.out.println(m.getCapacity());
           if((bookings+tikt.getTicket())<=m.getCapacity())
           {
             boolean ans = TicketDAO.bookTicket(tikt);
            if(ans)
            {
                JOptionPane.showMessageDialog(this,"Ticket Booked Successfully!!");
                clearAll();
            }  
           } 
           else{
               JOptionPane.showMessageDialog(this,"House Full !!");
               // jcMov_name.setSelectedIndex(0);
               clearAll();
           }
               
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "DB Error!!");
            e.printStackTrace();
            return;
        } catch (ParseException ex) {
           JOptionPane.showMessageDialog(this,"Parse Exception");
           ex.printStackTrace();
           return;
    }//GEN-LAST:event_btnBookTicktActionPerformed
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookTicketFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookTicketFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookTicketFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookTicketFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookTicketFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBookTickt;
    private com.toedter.calendar.JDateChooser jDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> jcMov_name;
    private javax.swing.JTextField txtContact;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtScreen;
    private javax.swing.JTextField txtTicket;
    private javax.swing.JTextField txtUser_name;
    // End of variables declaration//GEN-END:variables

public void loadMovieName(){
    try {
        
        ArrayList<String> list = new ArrayList<String>();
        map = MovieDao.getAllMovieName();
        if(map.isEmpty())
        {
            JOptionPane.showMessageDialog(this,"No Records Found!!");
            return;
        }
        for(Entry<String,Movies> e:map.entrySet())
        {
            list.add(e.getKey());
        }
        for(String name:list)
        {
            System.out.println(name);
            jcMov_name.addItem(name);
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this,"DB Error!!");
        e.printStackTrace();
    }
}

private boolean validateInput()
{
    mov_name = jcMov_name.getSelectedItem().toString();
    user_name = txtUser_name.getText();
    screen = txtScreen.getText().trim();
   ticket_date = jDate.getDate();
   ticket = Integer.parseInt(txtTicket.getText().trim());
   price = Double.parseDouble(txtPrice.getText().trim());
    contact = txtContact.getText().trim();
    
    if(mov_name.isEmpty()||user_name.isEmpty()||screen.isEmpty()||txtTicket.getText().isEmpty()||ticket_date==null||contact.isEmpty())
        return false;
    return true;
}

public void clearAll(){
    jcMov_name.setSelectedIndex(0);
    jDate.setCalendar(null);
    txtUser_name.setText("");
    txtContact.setText("");
    txtTicket.setText("");
    txtScreen.setText("");
    txtPrice.setText("");
}
}
